features = [
    # "era",
    "HT",
    # "sigma_higgs1", 
    "sigma_over_higgs1_reco_mass",
    "higgs1_reco_pt", "higgs1_reco_eta", 
    # "higgs1_reco_phi", 
    "higgs1_reco_mass",
    # "sigma_higgs2", 
    "sigma_over_higgs2_reco_mass",
    "higgs2_reco_pt", "higgs2_reco_eta", 
    #"higgs2_reco_phi", 
    "higgs2_reco_mass",
    "hh_vec_mass", "hh_vec_pt", "hh_vec_eta", 
    #"hh_vec_phi", "hh_vec_DeltaR", 
    "hh_vec_DeltaPhi", "hh_vec_DeltaEta", 
    # "hh_vec_ptOmass",
    # "njet",
    "higgs1_reco_jet1_pt", "higgs1_reco_jet1_eta", "higgs1_reco_jet1_phi", "higgs1_reco_jet1_mass",
    "higgs1_reco_jet2_pt", "higgs1_reco_jet2_eta", "higgs1_reco_jet2_phi", "higgs1_reco_jet2_mass",
    # "higgs1_DeltaPhijj", "higgs1_DeltaEtajj", 
    "higgs1_DeltaRjj",
    "higgs2_reco_jet1_pt", "higgs2_reco_jet1_eta", "higgs2_reco_jet1_phi", "higgs2_reco_jet1_mass",
    "higgs2_reco_jet2_pt", "higgs2_reco_jet2_eta", "higgs2_reco_jet2_phi", "higgs2_reco_jet2_mass",
    # "higgs2_DeltaPhijj", "higgs2_DeltaEtajj", 
    "higgs2_DeltaRjj",
    "minDeltaR_Higgjj", "maxDeltaR_Higgjj",
    # "higgs1_helicityCosTheta", "higgs2_helicityCosTheta",
    # "hh_CosThetaStar_CS"#,
    # "higgs_ST",
    # "jet1pt_pt", "jet2pt_pt", "jet3pt_pt", "jet4pt_pt",
    # "add_jet1pt_pt", "add_jet1pt_eta", "add_jet1pt_phi", "add_jet1pt_mass",
    # "add_jet1pt_Higgs1_deta", "add_jet1pt_Higgs1_dphi", "add_jet1pt_Higgs1_m",
    # "add_jet1pt_Higgs2_deta", "add_jet1pt_Higgs2_dphi", "add_jet1pt_Higgs2_m"
]
